# Generated by Django 5.0.4 on 2024-04-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='pno',
            field=models.IntegerField(),
        ),
    ]
